const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let me,daily=[],validDates=[],prediction,weatherData=[],driverData={},hourlyPrices={};
async function api(path,opts={}){const u=new URL(path,location.origin),d=window.PUBLIC_DATA;if(u.pathname==='/api/me'||u.pathname==='/api/login')return {username:'viewer',role:'viewer'};if(u.pathname==='/api/daily')return d.daily;if(u.pathname==='/api/dates')return d.dates;if(u.pathname==='/api/hourly-prices')return d.hourlyPrices||{};if(u.pathname==='/api/prediction')return d.prediction;if(u.pathname==='/api/weather')return d.weather;if(u.pathname==='/api/deviations')return d.deviations[u.searchParams.get('date')||'all'];if(u.pathname==='/api/drivers')return d.drivers[u.searchParams.get('date')||'all'];throw Error('公开版不支持此操作')}function fmt(v,n=2){return v==null?"—":Number(v).toFixed(n)}
function showApp(u){me=u;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userBadge').textContent=`${u.username} · ${u.role==='admin'?'管理员':'查看者'}`;if(u.role!=='admin')$$('.admin-only').forEach(x=>x.remove());loadAll()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{showApp(await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})}))}catch(x){$('#loginError').textContent=x.message}};$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');$('#pageTitle').textContent=b.textContent;if(b.dataset.view==='data')loadFiles()});
async function loadAll(){const [d,dates,p,v,w,drivers,hourly]=await Promise.all([api('/api/daily'),api('/api/dates'),api('/api/prediction'),api('/api/deviations'),api('/api/weather'),api('/api/drivers'),api('/api/hourly-prices')]);daily=d;validDates=dates;prediction=p;driverData=drivers;hourlyPrices=hourly;$('#tradeDate').innerHTML='<option value="">全部有效日期</option>'+dates.map(x=>`<option value="${x}">${x}</option>`).join('');refreshDateViews(v);renderDrivers();renderPrediction();weatherData=w.rows||[];renderWeather(w)}
function currentDaily(){const selected=$('#tradeDate').value;return daily.filter(r=>validDates.includes(r.trade_date)&&(!selected||r.trade_date===selected))}
function refreshCards(){const rows=currentDaily(),da=rows.map(r=>r.day_ahead_avg_yuan_mwh).filter(v=>v!=null),rt=rows.map(r=>r.real_time_avg_yuan_mwh).filter(v=>v!=null),sp=rows.map(r=>r.rt_minus_da_yuan_mwh).filter(v=>v!=null);$('#days').textContent=rows.length;$('#avgDA').textContent=fmt(da.reduce((a,b)=>a+b,0)/(da.length||1));$('#avgRT').textContent=fmt(rt.reduce((a,b)=>a+b,0)/(rt.length||1));$('#avgSpread').textContent=fmt(sp.reduce((a,b)=>a+b,0)/(sp.length||1))}
function refreshDateViews(v){refreshCards();drawLine();drawScatter();renderDaily();renderDeviation(v)}
$('#tradeDate').onchange=async()=>{const d=$('#tradeDate').value,q=d?`?date=${encodeURIComponent(d)}`:'';const [v,drivers]=await Promise.all([api('/api/deviations'+q),api('/api/drivers'+q)]);driverData=drivers;refreshDateViews(v);renderDrivers()};
function axes(svg,w,h,p){svg.innerHTML=`<line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#b9c7d2"/><line x1="${p}" y1="${p}" x2="${p}" y2="${h-p}" stroke="#b9c7d2"/>`}
function lineChart(svg,series,w=900,h=310,p=45){axes(svg,w,h,p);const vals=series.flatMap(s=>s.values).filter(v=>v!=null),mi=Math.min(...vals),ma=Math.max(...vals),n=Math.max(...series.map(s=>s.values.length)),x=i=>p+i*(w-2*p)/(n-1||1),y=v=>h-p-(v-mi)*(h-2*p)/(ma-mi||1);series.forEach(s=>{const pts=s.values.map((v,i)=>v==null?null:`${x(i)},${y(v)}`).filter(Boolean).join(' ');svg.insertAdjacentHTML('beforeend',`<polyline points="${pts}" fill="none" stroke="${s.color}" stroke-width="3" stroke-dasharray="${s.dash||''}"/>`)});[mi,ma].forEach(v=>svg.insertAdjacentHTML('beforeend',`<text x="5" y="${y(v)+4}" fill="#6d7b88" font-size="13">${v.toFixed(0)}</text>`));return{x,y}}
function drawLine(){const svg=$('#priceChart'),selected=$('#tradeDate').value,rows=currentDaily();if(selected&&hourlyPrices[selected]){const hp=hourlyPrices[selected],series=[{values:hp.map(r=>r.day_ahead_price),color:'#2176ae',name:'日前'},{values:hp.map(r=>r.real_time_price),color:'#f28e2b',name:'实时'}],map=lineChart(svg,series);$('#priceChartNote').textContent=selected+'｜24小时价格曲线，悬停数据点查看具体数值';series.forEach(s=>s.values.forEach((v,i)=>{if(v==null)return;svg.insertAdjacentHTML('beforeend','<circle cx="'+map.x(i)+'" cy="'+map.y(v)+'" r="4.5" fill="'+s.color+'" stroke="white" stroke-width="2"><title>'+selected+' '+String(i).padStart(2,'0')+':00｜'+s.name+' '+fmt(v)+' 元/MWh</title></circle>')}));for(let i=0;i<24;i+=3)svg.insertAdjacentHTML('beforeend','<text x="'+map.x(i)+'" y="292" text-anchor="middle" fill="#6d7b88" font-size="12">'+String(i).padStart(2,'0')+':00</text>');return}$('#priceChartNote').textContent='日均价格走势；选择具体日期后显示24小时曲线';const map=lineChart(svg,[{values:rows.map(r=>r.day_ahead_avg_yuan_mwh),color:'#2176ae',name:'日前'},{values:rows.map(r=>r.real_time_avg_yuan_mwh),color:'#f28e2b',name:'实时'}]);rows.forEach((r,i)=>[['日前',r.day_ahead_avg_yuan_mwh,'#2176ae'],['实时',r.real_time_avg_yuan_mwh,'#f28e2b']].forEach(([name,v,color])=>{if(v==null)return;svg.insertAdjacentHTML('beforeend','<circle cx="'+map.x(i)+'" cy="'+map.y(v)+'" r="4" fill="'+color+'"><title>'+r.trade_date+'｜'+name+'均价 '+fmt(v)+' 元/MWh</title></circle>')}))}
function drawScatter(){const svg=$('#scatterChart'),w=900,h=410,p=55,pts=currentDaily().filter(r=>r.actual_space_mw!=null&&r.real_time_avg_yuan_mwh!=null);axes(svg,w,h,p);if(!pts.length)return;const xs=pts.map(r=>r.actual_space_mw),ys=pts.map(r=>r.real_time_avg_yuan_mwh),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),x=v=>p+(v-xmin)*(w-2*p)/(xmax-xmin||1),y=v=>h-p-(v-ymin)*(h-2*p)/(ymax-ymin||1);pts.forEach(r=>svg.insertAdjacentHTML('beforeend',`<circle cx="${x(r.actual_space_mw)}" cy="${y(r.real_time_avg_yuan_mwh)}" r="7" fill="#2176ae"><title>${r.trade_date}｜${fmt(r.actual_space_mw)} MW｜${fmt(r.real_time_avg_yuan_mwh)}</title></circle>`))}
function renderDaily(){$('#dailyRows').innerHTML=currentDaily().filter(r=>r.actual_space_mw!=null).map(r=>`<tr><td>${r.trade_date}</td><td>${fmt(r.forecast_space_mw)}</td><td>${fmt(r.actual_space_mw)}</td><td>${fmt(r.day_ahead_avg_yuan_mwh)}</td><td>${fmt(r.real_time_avg_yuan_mwh)}</td><td>${fmt(r.rt_minus_da_yuan_mwh)}</td></tr>`).join('')}
function renderPrediction(){const m=prediction.metric,back=prediction.rows.filter(r=>r.prediction_type==='回测'),future=prediction.rows.filter(r=>r.prediction_type==='预测');$('#predMae').textContent=fmt(m.mae);$('#predRmse').textContent=fmt(m.rmse);$('#predN').textContent=m.sample_hours;$('#maeNote').textContent=`相当于平均每度电偏差 ${fmt(m.mae/10,2)} 分`;$('#modelName').textContent=m.model_name;$('#modelNote').textContent=`训练 ${m.train_start} 至 ${m.train_end}，留出 ${m.backtest_date} 回测。`;const svg=$('#forecastChart'),map=lineChart(svg,[{values:future.map(r=>r.predicted_price),color:'#2176ae'},{values:back.map(r=>r.actual_price),color:'#f28e2b',dash:'5 5'}],900,360,50);back.forEach((r,i)=>svg.insertAdjacentHTML('beforeend',`<circle cx="${map.x(i)}" cy="${map.y(r.actual_price)}" r="4" fill="#f28e2b"/>`));$('#predictionRows').innerHTML=prediction.rows.map(r=>`<tr><td>${r.target_date}</td><td>${String(r.trade_hour).padStart(2,'0')}:00</td><td>${r.prediction_type}</td><td>${fmt(r.predicted_price)}</td><td>${fmt(r.actual_price)}</td><td>${fmt(r.lower_price)}</td><td>${fmt(r.upper_price)}</td></tr>`).join('')}
function renderDeviation(v){$('#deviationRows').innerHTML=v.summary.map(r=>`<tr><td>${r.metric_name}</td><td>${fmt(r.day_ahead_mae)}</td><td>${fmt(r.intraday_mae)}</td><td>${fmt(r.day_ahead_bias)}</td><td>${fmt(r.intraday_bias)}</td><td>${r.sample_hours}</td></tr>`).join('');const rel=v.relationships.filter(r=>r.correlation!=null).slice(0,6);$('#relationList').innerHTML=rel.length?rel.map(r=>`<div class="insight"><b>${r.metric_name} · ${r.feature_name}</b><p>与实时－日前价差相关系数：<strong>${fmt(r.correlation,3)}</strong>（${r.sample_count} 小时）</p></div>`).join(''):'<div class="insight"><b>当前为单日视图</b><p>相关系数需要多个日期共同计算；选择“全部有效日期”查看关系排名。</p></div>'}
function renderDrivers(){const target=$('#driverTarget').value,rows=(driverData[target]||[]).slice(0,6),label=target==='realTimePrice'?'实时价格':'实时－日前价差',date=$('#tradeDate').value;$('#driverScope').textContent=`${date||'全部有效日期'}｜观察 ${label}｜条形越长，关系越明显`;if(!rows.length){$('#driverSummary').innerHTML='<strong>当前样本无法计算</strong>';$('#driverList').innerHTML='';return}const top=rows[0],direction=top.effect_100mw>=0?'推高':'压低';$('#driverSummary').innerHTML=`<span>当前最明显因素</span><strong>${top.metric_name}的${top.feature_name}</strong><p>增加 100 MW 时，${label}估算${direction} <b>${fmt(Math.abs(top.effect_100mw))}</b> 元/MWh</p>`;const max=Math.max(...rows.map(r=>Math.abs(r.correlation)));$('#driverList').innerHTML=rows.map((r,i)=>{const up=r.effect_100mw>=0,w=Math.max(5,Math.abs(r.correlation)/max*100),strength=Math.abs(r.correlation)>=.7?'强':Math.abs(r.correlation)>=.4?'中等':'较弱';return `<article class="driver-row"><div class="driver-rank">${i+1}</div><div class="driver-body"><div class="driver-title"><strong>${r.metric_name} · ${r.feature_name}</strong><span class="${up?'up':'down'}">${up?'推高':'压低'} ${fmt(Math.abs(r.effect_100mw))} 元/MWh / 100 MW</span></div><div class="driver-track"><i class="${up?'up':'down'}" style="width:${w}%"></i></div><p><b>${strength}关系</b>（相关系数 ${fmt(r.correlation,3)}，${r.sample_count} 小时）。${r.reason}</p></div></article>`}).join('')}
$('#driverTarget').onchange=renderDrivers;
async function loadFiles(){if(me.role!=='admin')return;const rows=await api('/api/files');$('#fileRows').innerHTML=rows.map(r=>`<tr><td>${r.file_name}</td><td>${(r.file_size/1024).toFixed(1)} KB</td><td>${r.detected_at.replace('T',' ')}</td><td><span class="tag">${r.status}</span></td><td>${r.message||''}</td></tr>`).join('')||'<tr><td colspan="5">待导入目录暂无文件</td></tr>'}$('#scanBtn').onclick=async()=>{const r=await api('/api/scan',{method:'POST'});await loadFiles();alert(`扫描完成，新增 ${r.newFiles} 个文件记录。`)};api('/api/me').then(showApp).catch(()=>{});

function weatherLevel(text){text=text||'';if(/暴雨|大雨|中雨|雷/.test(text))return ['降雨明显','偏弱','偏弱'];if(/小雨|阵雨|雨/.test(text))return ['可能降雨','一般','偏弱'];if(/阴/.test(text))return ['无明显降雨','一般','一般'];if(/多云/.test(text))return ['无明显降雨','一般','较好'];if(/晴/.test(text))return ['无明显降雨','一般','良好'];return ['待判断','待判断','待判断']}
function renderWeather(payload){const n=Number($('#weatherDays')?.value||7),rows=weatherData.slice(0,n);if(!rows.length){$('#weatherCards').innerHTML='<p class="muted">暂无天气缓存，请使用管理员账号更新。</p>';return}const highs=rows.map(r=>r.high_temp_c).filter(v=>v!=null),lows=rows.map(r=>r.low_temp_c).filter(v=>v!=null);$('#weatherHigh').textContent=fmt(Math.max(...highs),0);$('#weatherLow').textContent=fmt(Math.min(...lows),0);$('#rainDays').textContent=rows.filter(r=>/雨|雷/.test((r.day_weather||'')+(r.night_weather||''))).length;$('#solarDays').textContent=rows.filter(r=>['较好','良好'].includes(weatherLevel(r.day_weather)[2])).length;$('#weatherUpdated').textContent=payload.updatedAt?`最近更新：${payload.updatedAt.replace('T',' ')}｜来源：${payload.source}`:'等待更新';$('#weatherCards').innerHTML=rows.map(r=>{const [rain,wind,solar]=weatherLevel((r.day_weather||'')+' '+(r.night_weather||''));return `<article class="weather-card"><time>${r.forecast_date}</time><h4>${r.day_weather||'—'} / ${r.night_weather||'—'}</h4><div class="temperature"><strong>${fmt(r.high_temp_c,0)}°</strong><span>${fmt(r.low_temp_c,0)}°</span></div><ul><li><b>降雨</b><span>${rain}</span></li><li><b>风向</b><span>${r.day_wind||'—'} / ${r.night_wind||'—'}</span></li><li><b>风电条件</b><span>${wind}</span></li><li><b>光伏条件</b><span>${solar}</span></li></ul></article>`}).join('')}
$('#weatherDays').onchange=()=>renderWeather({rows:weatherData,updatedAt:weatherData[0]?.fetched_at,source:'中央气象台'});$('#weatherRefresh').onclick=async()=>{const r=await api('/api/weather/refresh',{method:'POST'});const w=await api('/api/weather');weatherData=w.rows||[];renderWeather(w);alert(`天气已更新，共 ${r.rows} 天。`)};

